# Generated by Django 5.2.5 on 2025-11-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image'),
        ),
        migrations.AddField(
            model_name='user',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
