# Generated by Django 5.2.5 on 2025-11-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='post',
        ),
    ]
